name: ClangSharp.Pathogen
on:
  push:
    branches: ['*']
  pull_request:
  workflow_dispatch:
    inputs:
      will_publish_packages:
        description: "Publish packages?"
        default: "false"
      preview_release_version:
        description: "Preview release version"
        default: ""
      do_full_release:
        description: "Full release?"
        default: "false"
env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
jobs:
  build-llvm:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: Windows
            lib-path: build/bin/libclang.dll
            build-command: ./build-native.cmd
            artifact-name: LlvmBuildOutputs-Windows
          # We use Ubuntu 18.04 so that the binary is usable on systems using glibc 2.27 and later
          # If we want to support even older versions we should explore building libclang with https://github.com/wheybags/glibc_version_header
          - os: ubuntu-18.04
            name: Linux
            lib-path: build-linux/lib/libclang.so
            clang-resource-dir: build-linux/lib/clang/
            build-command: ./build-native.sh
            artifact-name: LlvmBuildOutputs-Linux
    name: Build LLVM - ${{matrix.name}}
    runs-on: ${{matrix.os}}
    steps:
      # ----------------------------------------------------------------------- Checkout
      - name: Checkout
        # We intentionally don't checkout submodules here
        # They will be restored as needed only if we need to build LLVM.
        uses: actions/checkout@v2

      # ----------------------------------------------------------------------- Setup Python
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # ----------------------------------------------------------------------- Get LLVM Revision
      - name: Get LLVM Revision
        id: llvm
        run: python .github/workflows/get-llvm-revision.py

      # ----------------------------------------------------------------------- Build LLVM
      - name: Load cached LLVM build outputs
        id: cached-llvm
        uses: actions/cache@v2
        with:
          # Bumped to -2 to include the Clang resource directory
          key: llvm-output-${{runner.os}}-${{steps.llvm.outputs.revision}}-2
          # These are the paths of the external files required in ClangSharp.Pathogen.Runtime.csproj
          # (Make sure this is syncronized with "Archive LLVM Outputs" below)
          path: |
            ${{matrix.lib-path}}
            ${{matrix.clang-resource-dir}}

      - name: Checkout LLVM
        if: steps.cached-llvm.outputs.cache-hit != 'true'
        run: git submodule update --init --recursive --depth=1

      - name: Install sccache
        id: sccache
        if: steps.cached-llvm.outputs.cache-hit != 'true'
        run: python .github/workflows/install-sccache.py

      - name: Load LLVM sccache
        id: cached-sccache
        if: steps.cached-llvm.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: ${{steps.sccache.outputs.root-directory}}
          key: sccache-cache-${{runner.os}}-${{steps.llvm.outputs.revision}}
          restore-keys: sccache-cache-${{runner.os}}-

      - name: Start sccache server
        if: steps.cached-llvm.outputs.cache-hit != 'true'
        run: sccache --start-server

      # The GitHub hosted runners do not have Ninja installed by default
      # We only need to do this on Linux since Visual Studio comes with a copy of Ninja and we end up picking that one up for Windows
      - name: Install Ninja
        if: steps.cached-llvm.outputs.cache-hit != 'true' && runner.os == 'Linux'
        run: sudo apt install --yes ninja-build

      - name: Build LLVM
        if: steps.cached-llvm.outputs.cache-hit != 'true'
        run: ${{matrix.build-command}}

      - name: Show sccache statistics
        if: steps.cached-llvm.outputs.cache-hit != 'true'
        run: sccache --show-stats

      # The GitHub Actions cache gets confused by the symlink so we need to remove it
      - name: Unsymlink libclang
        if: steps.cached-llvm.outputs.cache-hit != 'true' && runner.os == 'Linux'
        run: |
          cp ${{matrix.lib-path}} ${{matrix.lib-path}}-nosymlink
          rm ${{matrix.lib-path}}
          mv ${{matrix.lib-path}}-nosymlink ${{matrix.lib-path}}

      - name: Upload LLVM build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.artifact-name}}
          if-no-files-found: error
          # The paths listed here must match "Load cached LLVM build outputs" above
          path: |
            ${{matrix.lib-path}}
            ${{matrix.clang-resource-dir}}

  build-dotnet:
    name: Build ClangSharp.Pathogen
    runs-on: ubuntu-latest
    needs: build-llvm
    outputs:
      publish-to-github: ${{steps.configuration.outputs.publish-to-github}}
    steps:
      # ----------------------------------------------------------------------- Checkout
      - name: Checkout
        uses: actions/checkout@v2
        # Sadly we need to check out submodules here to make SourceLink happy.
        # (Ideally we'd just archive libclang.dll along with the handful of files ClangSharp.Pathogen.Runtime needs to build the NuGet package.)
        with:
          submodules: 'recursive'

      # ----------------------------------------------------------------------- Setup Python
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # ----------------------------------------------------------------------- Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      # ----------------------------------------------------------------------- Download LLVM Build
      - name: Download LLVM Windows build artifacts
        uses: actions/download-artifact@v2
        with:
          name: LlvmBuildOutputs-Windows
          path: build/bin/
      - name: Download LLVM Linux build artifacts
        uses: actions/download-artifact@v2
        with:
          name: LlvmBuildOutputs-Linux
          path: build-linux/lib/
      
      # ----------------------------------------------------------------------- Configure versioning
      - name: Configure build
        id: configuration
        run: python .github/workflows/configure-build.py
        env:
          github_event_name: ${{github.event_name}}
          github_repository_owner: ${{github.repository_owner}}
          github_run_number: ${{github.run_number}}
          github_ref: ${{github.ref}}
          is_official_source: ${{secrets.is_official_source}}
          input_will_publish_packages: ${{github.event.inputs.will_publish_packages}}
          input_preview_release_version: ${{github.event.inputs.preview_release_version}}
          input_do_full_release: ${{github.event.inputs.do_full_release}}

      # ----------------------------------------------------------------------- Build ClangSharp.Pathogen
      - name: Restore
        run: dotnet restore

      - name: Build
        id: build
        run: dotnet build --no-restore

      - name: Pack
        id: pack
        run: dotnet pack --no-build

      # ----------------------------------------------------------------------- Collect Artifacts
      - name: Collect Build Outputs
        uses: actions/upload-artifact@v2
        # We always want to collect build outputs when they were produced
        if: steps.build.outcome == 'success' && always()
        with:
          name: BuildOutputs
          path: |
            **/bin/**
            **/obj/**

      - name: Collect NuGet Packages
        uses: actions/upload-artifact@v2
        # We always want to collect packages when they were produced
        if: steps.pack.outcome == 'success' && always()
        with:
          name: Packages
          path: packages/**

  publish-packages:
    name: Publish ClangSharp.Pathogen
    runs-on: ubuntu-latest
    needs: build-dotnet
    if: needs.build-dotnet.outputs.publish-to-github == 'true'
    steps:
      # ----------------------------------------------------------------------- Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      # ----------------------------------------------------------------------- Download built packages
      - name: Download built packages
        uses: actions/download-artifact@v2
        with:
          name: Packages

      # ----------------------------------------------------------------------- Publish ClangSharp.Pathogen
      - name: Push packages
        run: dotnet nuget push "*.nupkg" --no-symbols true --api-key ${{secrets.GITHUB_TOKEN}} --source https://nuget.pkg.github.com/${{github.repository_owner}}
        env:
          # This is a workaround for https://github.com/NuGet/Home/issues/9775
          DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER: 0

  send-ci-failure-notification:
    name: Send CI Failure Notification
    needs: [build-llvm, build-dotnet, publish-packages]
    if: failure() && github.event_name != 'pull_request'
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      # ----------------------------------------------------------------------- Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # ----------------------------------------------------------------------- Setup Python
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      # ----------------------------------------------------------------------- Send CI Failure Notification
      - name: Send Notification
        run: python .github/workflows/send-ci-failure-notification.py
        env:
          webhook_url: ${{secrets.TEAMS_WEBHOOK_URL}}
          github_organization: ${{github.repository_owner}}
          github_repo: ${{github.repository}}
          github_workflow_name: ${{github.workflow}}
          github_run_number: ${{github.run_id}}
